platform :ios, '8.0'
use_frameworks!

target '___PROJECTNAME___' do
	pod 'Alamofire', '<= 3.6’
	pod 'ObjectMapper', '= 1.4.0'
	pod 'AsyncSwift', '< 2.0’
	pod 'Kingfisher', '~> 2.6'
	pod 'SAMKeychain'
	pod 'FBSDKLoginKit'
	pod 'Tapptitude', :path => '.'
	pod 'JLRoutes'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SwiftMessages', '~> 2.0.0'
	pod 'TextAttributes', '< 1.0'
	pod 'Stripe'
end