platform :ios, '10.0'
use_frameworks!

target '___PROJECTNAME___' do
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'SAMKeychain'
    pod 'FBSDKLoginKit'
    pod 'Tapptitude', :path => '.'
    pod 'JLRoutes'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftMessages'
    pod 'TextAttributes'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['TextAttributes'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
