platform :ios, '10.0'
use_frameworks!

target '___PROJECTNAME___' do
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'SAMKeychain'
    pod 'FBSDKLoginKit'
    pod 'Tapptitude', :path => '.'
    pod 'URLNavigator'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftMessages'
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if ['XXXXXX'].include? target.name
#            target.build_configurations.each do |config|
#                config.build_settings['XXXXXX'] = '3.2'
#            end
#        end
#    end
#end
